name: Check Host

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check host availability
        run: |
          HOST="example.com"  # Замените на ваш хост
          if ping -c 1 $HOST &> /dev/null; then
            echo "$HOST is reachable"
          else
            echo "$HOST is not reachable"
            exit 1
          fi

      - name: Check HTTP response
        run: |
          HOST="https://lenta.ru/"  # Замените на ваш хост
          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null $HOST)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "$HOST is up and running"
          else
            echo "$HOST returned status code $RESPONSE"
            exit 1
          fi
          - name: Debug network
            run: |
              echo "Current IP:"
              curl ifconfig.me
              echo "Checking access to another host..."
              HOST="example.com"  # Замените на другой хост
              if ping -c 1 $HOST &> /dev/null; then
                echo "$HOST is reachable"
              else
                echo "$HOST is not reachable"
                exit 1
              fi
